/* Generated by Together */

package com.chaosserver.data;

/**
 * Stores a list of constants used for bean loading and writing.
 */
public interface IJavaBeanXmlConstants {
    /** The Object node name. */
    public static String OBJECT_ELM = "Object";

    /** The attribute of the bean node to define the class it represents. */
    public static String CLASS_ATT = "class";

    /** The Bean node name. */
    public static String BEAN_ELM = "Bean";

    /** The property node name. */
    public static String PROPERTY_ELM = "Property";

    /** The attribute of the property node defining its name. */
    public static String NAME_ATT = "name";

    /** The Collection node name. */
    public static String COLLECTION_ELM = "Collection";

    /** The text element node name. */
    public static String TEXT_ELM = "#text";

    /** The finable node name. */
    public static String FINDABLE_ELM = "Findable";

    /** The finder class attribute. */
    public static String FINDER_CLASS_ATT = "finderClass";

    /** The finder key attribute. */
    public static String FINDER_KEY_ATT = "finderKey";

    /** The Map node name. */
    public static String MAP_ELM = "Map";
}
